name: Labeler
on:
  push:
    branches:
    - main
    - dev
  schedule:
    - cron: "0 2 * * 1-5"

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
